#!/usr/bin/env bash
set -e
paket=$1
dizin=$(pwd)

if [ ! -d ${paket} ]; then
echo "Bir paket değil!"
exit
fi
if [ ! -f "${paket}/bpsbuild" ]; then
echo "Paket dosyası bulunamadı!"
exit
fi

echo "Paket : $paket"

source ${paket}/bpsbuild
DESTDIR=/tmp/bps/build/rootfs-${name}-${version}
SOURCEDIR=/tmp/bps/build/${name}-${version}
BUILDDIR=/tmp/bps/build/build-${name}-${version}
#echo $name
#echo $version

initsetup()
{

	mkdir -p /tmp/bps
	mkdir -p /tmp/bps/build
	cd /tmp/bps/build
	rm -rf ./*
	rm -rf build-${name}-${version}*
	rm -rf ${name}-${version}*
	rm -rf rootfs-${name}-${version}*
	
	wget ${source}
	dowloadfile=$(ls|head -1)
	filetype=$(file -b --extension $dowloadfile|cut -d'/' -f1)
	echo "***********dosya gz ile sıkıştırılmış**********:${filetype}"
	if [ ${filetype} == "bz2" ]
	then
		tar -xvf ${dowloadfile}
	fi
	
	if [ ${filetype} == "tar" ]
	then
		tar -xvf ${dowloadfile}
	fi

	if [ ${filetype} == "xz" ]
	then
		tar -xvf ${dowloadfile}
	fi
	if [ "${filetype}" == "gz" ]
	then
	echo "***********dosya gz ile sıkıştırılmış**********"
		tar -xvf ${dowloadfile}
	fi
	#**********************************************************
	mkdir -p build-${name}-${version}
	mkdir -p rootfs-${name}-${version}
	
	cp ${dizin}/${paket}/bpsbuild /tmp/bps/build
	cd build-${name}-${version}
}

#********************************paket index******************************************************
paketindex()
{
	#find rootfs-${name}-${version}/*>${name}-${version}.index	
	rm -rf ${name}-${version}.index
	cd /tmp/bps/build/rootfs-${name}-${version}
	find . |
	    while IFS= read file_name; do
	    
	    	if [ -f ${file_name} ]; then
	    		echo ${file_name:1}>>../${name}-${version}.index
		fi
	    done
}
#*******************************xz compress****************************************


paketle()
{
cd /tmp/bps/build
tar -cf paket-${name}-${version}.tar rootfs-${name}-${version}/* ${name}-${version}.index bpsbuild

xz -9 paket-${name}-${version}.tar
cp paket-${name}-${version}.tar.xz ${dizin}/${paket}/${name}-${version}.bps
#rm -rf build-${name}-${version}*
#rm -rf ${name}-${version}*
}

echo "******************** initsetup *******************"
initsetup
echo "******************** setup **********************"
setup
echo "******************** build **********************"
build
echo "******************** package ********************"
package
echo "******************** paketindex *****************"
paketindex
echo "******************** paketle ********************"
paketle
