#!/usr/bin/env bash
version="2.5.1"
name="attr"
depends="glibc"
description=" kütüphanesi"
source="https://mirror.rabisu.com/savannah-nongnu/attr/${name}-${version}.tar.gz"
groups="sys.apps"
setup()
{
	../${name}-${version}/configure --prefix=/ \
        --sysconfdir=/etc \
        --libdir=/lib \
        --disable-selinux
	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


