#!/usr/bin/env bash
name="openrc"
release="1"
version="0.46"
depends=""
description="servis yöneticisi"
source="https://github.com/OpenRC/openrc/archive/refs/tags/$version.zip"
groups="sys.apps"
setup()
{
	mkdir -p /tmp/bps/build/extras
	cp ${dizin}/${paket}/extras/* /tmp/bps/build/extras/
	cp ${dizin}/${paket}/openrc.sysconf /tmp/bps/build/openrc.sysconf
	cp ${dizin}/${paket}/poweroff /tmp/bps/build/poweroff
	cp ${dizin}/${paket}/reboot /tmp/bps/build/reboot
	

	cd $SOURCEDIR
	 meson setup build \
        --sysconfdir=/etc \
        --libdir=/lib \
        --prefix=/ \
        -Ddefault_library=both \
        -Dzsh-completions=true \
        -Dbash-completions=true \
        -Dpkgconfig=true
        # -Dpam=$(use_opt pam true false) \
}
build()
{
	 ninja -C build
}
package()
{
	export DESTDIR=${DESTDIR}//
	ninja -C build install
	# disable all services
	rm -f ${DESTDIR}/etc/runlevels/*/*
	rm ${DESTDIR}//etc/init.d/functions.sh
	ln -s ../../lib/rc/sh/functions.sh ${DESTDIR}/etc/init.d/functions.sh
	# install sysconf script
	mkdir -p ${DESTDIR}/etc/sysconf.d/
	install ../openrc.sysconf ${DESTDIR}/etc/sysconf.d/openrc
	mkdir -p ${DESTDIR}/etc/group.d
	mkdir -p ${DESTDIR}/etc/passwd.d
	echo "uucp:x:14:" > ${DESTDIR}/etc/group.d/uucp
	echo "uucp:x:10:14:uucp:/var/spool/uucp:/bin/false" > ${DESTDIR}/etc/passwd.d/uucp
	# move /share to /usr/share
	mkdir -p ${DESTDIR}/usr ${DESTDIR}/sbin
	mv ${DESTDIR}/{,usr}/share
	# reboot and poweroff script
	install ../reboot ${DESTDIR}/sbin/reboot
	install ../poweroff ${DESTDIR}/sbin/poweroff
	ln -s openrc-shutdown ${DESTDIR}/sbin/shutdown
	# install extras
	mkdir -p ${DESTDIR}/usr/libexec
	
	install ../extras/disable-secondary-gpu.sh ${DESTDIR}/usr/libexec/disable-secondary-gpu
	install ../extras/disable-secondary-gpu.initd ${DESTDIR}/etc/init.d
	install ../extras/backlight-restore.initd ${DESTDIR}/etc/init.d
}


