#!/usr/bin/env bash
name="findutils"
release="1"
version="4.9.0"
depends="glibc,readline,ncurses"
description="modül ve sistem iletişimi sağlayan paket"
source="https://ftp.gnu.org/gnu/findutils/findutils-$version.tar.xz"
groups="sys.fs"
setup()
{
	../${name}-${version}/configure --prefix=/ \
        --libdir=/lib/
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


