#!/usr/bin/env bash
version="9.4"
name="coreutils"
depends="glibc,readline,ncurses"
description="temel uygulamalar"
source="https://ftp.gnu.org/gnu/coreutils/${name}-${version}.tar.xz"
groups="sys.apps"
setup()
{
	../${name}-${version}/configure --prefix=/ \
        --libdir=/lib \
        --libexecdir=/usr/libexec \
        --enable-largefile \
        --disable-selinux \
        --enable-single-binary=symlinks \
        --enable-no-install-program=groups,hostname,kill,uptime \
        $(use_opt openssl --with-openssl --without-openssl)
	
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


