#!/usr/bin/env bash
version="9.4"
name="coreutils"
depends=""
description="The basic file, shell and text manipulation utilities of the GNU operating system"
source="https://ftp.gnu.org/gnu/coreutils/${name}-${version}.tar.xz"
groups="app.arch"
setup()
{

        ../${name}-${version}/configure  --prefix=/usr \
        --libdir=/usr/lib64 \
        --libexecdir=/usr/libexec \
        --enable-largefile \
        --enable-no-install-program=groups,hostname,kill,uptime \
        $(use_opt openssl --with-openssl --without-openssl)
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
}


