#!/usr/bin/env bash
version="6.1"
name="kernel"
depends=""
description="temel dağıtım kernel dosyası"
source=""
groups="sys.base"
setup()
{
	echo ""
}
build()
{
	echo ""
}
package()
{
	mkdir -p ${DESTDIR}/boot
	cp -prfv $dizin/$name/vmlinuz  ${DESTDIR}/boot/
}


