#!/usr/bin/env bash
version="31"
name="kmod"
depends="glibc,zlib"
description="kmod uygulaması"
source="https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kmod/${name}-${version}.tar.xz"
groups="sys.apps"
setup()
{
	../${name}-${version}/configure --prefix=/ \
        --libdir=/lib/ \
        --bindir=/sbin
        
	   # remove xsltproc dependency
	   rm -f man/Makefile
	   echo -e "all:\ninstall:" > man/Makefile
}
build()
{
	make 
}
package()
{
	make install DESTDIR=$DESTDIR
	cd $DESTDIR/sbin
	for target in depmod insmod modinfo modprobe rmmod; do
  	ln -sfv kmod $target
	done
	
	mkdir -p $DESTDIR/bin
	cd $DESTDIR/bin
	ln -sfv ../sbin/kmod lsmod
}


