#!/bin/bash
boot=$HOME/distro/deneme
rm -rf $boot

mkdir -p $HOME/distro
mkdir -p $boot
mkdir -p $boot/bin
./bpsupdate
./bpskur glibc $boot/
./bpskur readline $boot/
./bpskur ncurses $boot/
./bpskur busybox $boot/
./bpskur kmod $boot/
./bpskur eudev $boot/
./bpskur util-linux $boot/
./bpskur base-file $boot/
./bpskur grub $boot/
./bpskur e2fsprogs $boot/
#****************modul yukleme*************************
#cd $HOME/distro/linux-6.6.2
#make bzImage modules
#INSTALL_MOD_PATH="$HOME/distro/initrd" make modules_install
#/sbin/depmod --all --basedir=initrd #modul indeksi oluşturluyor
mkdir -p $boot/lib/modules/
mkdir -p $boot/lib/modules/$(uname -r)
mkdir -p $boot/lib/modules/$(uname -r)/moduller
#moduller {cdrom,loop,md,ahci,block,ata,firewire,sd,scsi,message,pcmcia,virtio,host}
#moduller {storage,crypto,fs,lib,dm-snapshot,overlay,isofs,squashfs,hfsplus,sr_mod,dm_mod}
#moduller {nls,nls_utf8,overlayfs,udf,ext4,usb-storage}

#for directory in {lib,fs,crypto,net} \
#   drivers/{usb,block,ata,md,firewire} \
#    drivers/{scsi,message,pcmcia,virtio} ;
#   	do
    	#echo ${directory}
    	#    misc \
#  find /lib/modules/$(uname -r)/kernel/${directory}/ -type f \
#      -exec install {} $HOME/distro/initrd/lib/modules/$(uname -r)/moduller/ \;
#	done
#cp -prvf $HOME/boot/initrd/lib/modules/$(uname -r)/kernel/* $boot/lib/modules/$(uname -r)/moduller/ #sistemden kopyalandı..
cp /lib/modules/$(uname -r)/kernel/* -prvf $boot/lib/modules/$(uname -r)/moduller/ #sistemden kopyalandı..
/sbin/depmod --all --basedir=$boot #modul indeksi oluşturluyor
#*****************kurallar yüklenecek*************************
mkdir -p $boot/etc/udev/
mkdir -p $boot/lib/udev/
##cp /etc/udev/rules.d -rf  $boot/etc/udev/
##cp /lib/udev/rules.d -rf  $boot/lib/udev/

#cp $HOME/boot/initrd/etc/udev/rules.d -rf  $boot/etc/udev/
#cp $HOME/boot/initrd/lib/udev/rules.d -rf  $boot/lib/udev/
#cp /etc/udev/rules.d -rf  $boot/etc/udev/
#cp /lib/udev/rules.d -rf  $boot/lib/udev/

#rm -rf $HOME/distro/initrd/lib/udev/rules.d/80-drivers.rules
#rm -rf $HOME/distro/initrd/lib/udev/rules.d/80-debian-compat.rules
#rm -rf $boot/lib/udev/rules.d/80-net-setup-link.rules
#rm -rf $boot/lib/udev/rules.d/73-seat-late.rules
#rm -rf $boot/etc/udev/rules.d/40-libsane.rules
#rm -rf $boot/etc/udev/rules.d/S99-2000S1.rules

#rm -rf $HOME/distro/initrd/lib/udev/rules.d/90-nm-thunderbolt.rules
#rm -rf $HOME/distro/initrd/lib/udev/rules.d/73-seat-late.rules


cd $boot
find |cpio -H newc -o >../boot-initrd.img



#************************iso *********************************
mkdir -p $HOME/distro/iso
mkdir -p $HOME/distro/iso/boot
mkdir -p $HOME/distro/iso/boot/grub
mkdir -p $HOME/distro/iso/live || true

#iso dizinine vmlinuz ve initrd.img dosyamız kopyalanıyor
#cp $HOME/distro/linux-6.6.2/arch/x86/boot/bzImage $HOME/distro/iso/boot/vmlinuz 
cp /boot/vmlinuz-$(uname -r) $HOME/distro/iso/boot/vmlinuz  #sistemde kullandığım kerneli kopyaladım istenirde kernel derlenebilir.
zstd  $HOME/distro/boot-initrd.img -10
mv $HOME/distro/boot-initrd.img.zst $HOME/distro/boot-initrd.img #oluşturduğumuz **initrd.img** dosyamızı taşıyoruz.
mv $HOME/distro/boot-initrd.img $HOME/distro/iso/boot/initrd.img #oluşturduğumuz **initrd.img** dosyamızı taşıyoruz.

echo 'menuentry "Linux GNU/Linux 64-bit" --class liveiso  {' > $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz net.ifnames=0 biosdevname=0 ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Disk GNU/Linux 64-bit" --class liveiso  {' > $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz net.ifnames=0 biosdevname=0 init=/bin/initdisk ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Live GNU/Linux 64-bit" --class liveiso  {' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz init=/bin/canli ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Kur iki Part GNU/Linux 64-bit" --class liveiso  {' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz init=/bin/kur2 ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Kur-Tek Part GNU/Linux 64-bit" --class liveiso  {' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz init=/bin/kur' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

echo 'menuentry "Kur UEFI GNU/Linux 64-bit" --class liveiso  {' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz init=/bin/kuruefi ' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> $HOME/distro/iso/boot/grub/grub.cfg
echo '}' >> $HOME/distro/iso/boot/grub/grub.cfg

#grub-mkrescue $HOME/distro/iso/ -o $HOME/distro/distro.iso
#qemu-system-x86_64 -cdrom $HOME/distro/distro.iso -m 1G





